#!/usr/bin/perl -w
use v5.30;
use Data::Dumper;

$^I = '';

while (<>) {
    s/\{-# LINE 1 "Sdf.hs" #-\}/{-# LANGUAGE DeriveGeneric #-}/;
    if (/^import Prelude/) {
        $_ = "import GHC.Generics (Generic(..))\n$_";
    }
    s/^data (\S++)/instance ATermConvertible $1\n$&/;
    s/deriving \( Data, Typeable, Show \)/deriving (Data, Typeable, Generic, Show)/;
    if ($_ eq "{-* Generated by DrIFT : Look, but Don't Touch. *-}\n" .. !!0) {
        $_ = "-- $_";
    }
    print;
}
